#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App6.Resource", IsApplication=true)]

namespace App6
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fastfood = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_create = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_redo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_content_save = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_content_undo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_social_share = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo_mio = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mio = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int windowStyle = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int editText1 = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int image1 = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int imageMainIcon = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int imageView1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int imageView2 = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int kafe_adress = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int kafe_title = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int listView = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int listViewKafe = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int logo_kafe = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int menu_settings = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int menu_share = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int textViewMainTitle = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int toolbar = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int KafeMain = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int KafeMainAdapter = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int mainAdapter = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int toolbar = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int home = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int photo_edit = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int st1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int st2 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int st3 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int st4 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int st5 = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
